neurolib:
  learning_rate: 0.001
  train_epochs: 10

nrel_solar_power:
  learning_rate: 0.001
  train_epochs: 10

atec:
  learning_rate: 0.001
  train_epochs: 10

smart_meters_in_london:
  learning_rate: 0.001
  train_epochs: 10

global_temp:
  learning_rate: 0.001
  train_epochs: 10

global_wind:
  learning_rate: 0.001
  train_epochs: 10

largest_ca:
  learning_rate: 0.001
  train_epochs: 10

largest_gla:
  learning_rate: 0.001
  train_epochs: 10

largest_gba:
  learning_rate: 0.001
  train_epochs: 10

china_air_quality:
  learning_rate: 0.001
  train_epochs: 10

sirs:
  learning_rate: 0.001
  train_epochs: 10

sp500:
  learning_rate: 0.001
  train_epochs: 10

m5:
  learning_rate: 0.001
  train_epochs: 10

measles_england:
  learning_rate: 0.001
  train_epochs: 10

wikipedia_web_traffic:
  learning_rate: 0.001
  train_epochs: 10

google_community_mobility:
  learning_rate: 0.001
  train_epochs: 10

rebound:
  learning_rate: 0.001
  train_epochs: 10

wikipedia_web_traffic_2000:
  learning_rate: 0.001
  train_epochs: 10

wikipedia_web_traffic_20000:
  learning_rate: 0.001
  train_epochs: 10
