neurolib:
  enc_in: 2000
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg
  

nrel_solar_power:
  enc_in: 5162
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

atec:
  enc_in: 1569
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

smart_meters_in_london:
  enc_in: 2898
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

global_temp:
  enc_in: 3774
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

global_wind:
  enc_in: 3696
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

largest_ca:
  enc_in: 7491
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

largest_gla:
  enc_in: 3376
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

largest_gba:
  enc_in: 2229
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 3
  down_sampling_layers: 3
  down_sampling_window: 2
  down_sampling_method: avg

china_air_quality:
  enc_in: 1105
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

sirs:
  enc_in: 2994
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

sp500:
  enc_in: 1475
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

m5:
  enc_in: 3049
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 3
  down_sampling_layers: 3
  down_sampling_window: 2
  down_sampling_method: avg

measles_england:
  enc_in: 1161
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

wikipedia_web_traffic:
  enc_in: 112333
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 1
  down_sampling_layers: 3
  down_sampling_window: 2
  down_sampling_method: avg

google_community_mobility:
  enc_in: 5826
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

rebound:
  enc_in: 6000
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

wikipedia_web_traffic_2000:
  enc_in: 2000
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg

wikipedia_web_traffic_2000:
  enc_in: 20000
  train_epochs: 10
  learning_rate: 0.001
  d_model: 32
  d_ff: 64
  e_layers: 2
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: avg